from pydantic import BaseModel, Field


class PlanStep(BaseModel):
    """
    Represents a single execution step.
    """

    order: int

    title: str

    description: str


class ExecutionPlan(BaseModel):
    """
    Complete execution plan generated by the Planner.
    """

    steps: list[PlanStep] = Field(default_factory=list)